_target_: MolecularDiffusion.runmodes.generate.GenerativeFactory
task_type: outpaintft
sampling_mode: "ddpm"
num_generate: 100
mol_size:  [76,76]
target_values: [] 
property_names: []
batch_size: 1
seed: 86
visualize_trajectory: False
output_path: generated_mol
condition_configs:
  reference_structure_path: "data/template_structures/INT2_0.xyz"
  t_start: 1
  n_frames: 0
  n_retrys: 0
  t_retry: 180

