_target_: MolecularDiffusion.runmodes.generate.GenerativeFactory
task_type: inpaint
sampling_mode: "ddpm"
num_generate: 100
mol_size:  [0,0]
target_values: [] 
property_names: []
batch_size: 1
seed: 86
visualize_trajectory: False
output_path: generated_mol
condition_configs:
  reference_structure_path: "data/template_structures/BINOLCpHHH.xyz"
  condition_component: xh
  mask_node_index: 
  - 5
  - 30
  - 31
  - 6
  - 7
  - 45
  - 8
  - 32
  - 9
  - 10 
  - 33
  - 11
  - 34
  - 12
  - 35 
  - 13
  - 36
  - 14
  - 15 
  - 16
  - 17
  - 18
  - 37
  - 19
  - 38
  - 20
  - 39
  - 21
  - 40
  - 22
  - 23
  - 41
  - 24
  - 44
  - 25
  - 26
  - 43
  - 42
  denoising_strength: 0.75
  t_start: 0.8
  t_critical_1: 0.8
  t_critical_2: 1
  d_threshold_f: 1.5
  w_b: 10
  all_frozen: True
  use_covalent_radii: True
  scale_factor: 1.2
  noise_initial_mask: True
  n_frames: 0
  n_retrys: 0
  t_retry: 180

