_target_: MolecularDiffusion.runmodes.generate.GenerativeFactory
task_type: inpaint_cfg
sampling_mode: "ddpm"
num_generate: 100
mol_size:  [0,0]
target_values: [3,1.5] 
property_names: ["S1_exc", "T1_exc"]
batch_size: 1
seed: 86
n_frames: 0
output_path: generated_mol
condition_configs:
  cfg_scale: 1
  reference_structure_path: "data/template_structures/INT2_0.xyz"
  t_start: 0.8
  t_critical: 0.05

  # inpaint
  # denoising_strength: 0.7
  # noise_initial_mask: False
  # mask_node_index: 
  # - 5
  # - 30
  # - 31


