_target_: MolecularDiffusion.runmodes.generate.GenerativeFactory
task_type: unconditional
sampling_mode: "ddpm"
num_generate: 100
mol_size:  [16]
target_values: []
property_names: []
batch_size: 1
seed: 86
n_frames: 0
output_path: generated_mol