_target_: MolecularDiffusion.runmodes.generate.GenerativeFactory
task_type: outpaint
sampling_mode: "ddpm"
num_generate: 100
mol_size:  [0,0]
target_values: [] 
property_names: []
batch_size: 1
seed: 86
visualize_trajectory: False
output_path: generated_mol
condition_configs:
  reference_structure_path: "template.xyz"
  n_frames: 0
  n_retrys: 3
  t_retry: 180

