_target_: MolecularDiffusion.runmodes.train.Logger
logger: logging # wandb, logging
log_interval: 2
name_wandb: MolecularDiffusion
project_wandb: MolecularDiffusion
dir_wandb: ${trainer.output_path}



