_target_: MolecularDiffusion.runmodes.train.ModelTaskFactory_EGCL
task_type: regression
atom_vocab: ${data.atom_vocab}
condition_names: []
hidden_size: 512
act_fn:
  _target_: torch.nn.ReLU
num_layers: 1
attention: True
tanh: True
num_sublayers: 5
sin_embedding: False
aggregation_method: "sum"
dropout: 0.0
normalization: True
include_cosine: True
norm_constant: 1.0
normalization_factor: 1.0
chkpt_path: "trained_models/egcl_reg_formed_s1t1_a3/regression-epoch=138-metric=0.1478.pkl"

# specific to regression
task_learn: [S1_exc,T1_exc]
criterion: mse
metric: [mae]
num_mlp_layer: 3
mlp_dropout: 0.2